/**
 * Translator Knowledge Beacon API
 * This is the Translator Knowledge Beacon web service application programming interface (API).  This OpenAPI (\"Swagger\") document may be used as the input specification into a tool like [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen/blob/master/README.md) to generate client and server code stubs implementing the API, in any one of several supported computer languages and frameworks. In order to customize usage to your web site, you should change the 'host' directive below to your hostname. 
 *
 * OpenAPI spec version: 1.0.11
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package bio.knowledge.client.api;

import bio.knowledge.client.ApiException;
import bio.knowledge.client.model.InlineResponse2002;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EvidenceApi
 */
public class EvidenceApiTest {

    private final EvidenceApi api = new EvidenceApi();

    
    /**
     * 
     *
     * Retrieves a (paged) list of annotations cited as evidence for a specified concept-relationship statement 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEvidenceTest() throws ApiException {
        String statementId = null;
        String keywords = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        // List<InlineResponse2002> response = api.getEvidence(statementId, keywords, pageNumber, pageSize);

        // TODO: test validations
    }
    
}
